// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-sna47d8Fadk94zjiJMKvAbmQ9xgRib0',
    appId: '1:546402300063:web:2afc7389c9b04cef59f2aa',
    messagingSenderId: '546402300063',
    projectId: 'caring-97647',
    authDomain: 'caring-97647.firebaseapp.com',
    storageBucket: 'caring-97647.firebasestorage.app',
    measurementId: 'G-B22RC2S2QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ZGhpKzSvf8TVNiiwrob47MVd1O3kJTA',
    appId: '1:546402300063:android:e1bf43d1242c15c759f2aa',
    messagingSenderId: '546402300063',
    projectId: 'caring-97647',
    storageBucket: 'caring-97647.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDPehFnSJ2u43SXJ-1SPCqx8cQ-ZQo7xg',
    appId: '1:546402300063:ios:20aa8b202650d29d59f2aa',
    messagingSenderId: '546402300063',
    projectId: 'caring-97647',
    storageBucket: 'caring-97647.firebasestorage.app',
    iosBundleId: 'com.example.caRing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDPehFnSJ2u43SXJ-1SPCqx8cQ-ZQo7xg',
    appId: '1:546402300063:ios:20aa8b202650d29d59f2aa',
    messagingSenderId: '546402300063',
    projectId: 'caring-97647',
    storageBucket: 'caring-97647.firebasestorage.app',
    iosBundleId: 'com.example.caRing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-sna47d8Fadk94zjiJMKvAbmQ9xgRib0',
    appId: '1:546402300063:web:6c02be201124c62d59f2aa',
    messagingSenderId: '546402300063',
    projectId: 'caring-97647',
    authDomain: 'caring-97647.firebaseapp.com',
    storageBucket: 'caring-97647.firebasestorage.app',
    measurementId: 'G-8ZDS3WHRYB',
  );
}
